apiVersion: '62.0'

standardObjects:
  - apiName: Account
    label: Account
    pluralLabel: Accounts
    description: Companies and organizations
    fields:
      - apiName: Name
        label: Account Name
        type: Text
        length: 255
      - apiName: Phone
        label: Phone
        type: Phone
      - apiName: Website
        label: Website
        type: Url
      - apiName: Industry
        label: Industry
        type: Picklist
        values: [Technology, Manufacturing, Financial Services, Healthcare, Retail, Media, Energy, Education, Government, Consulting, Other]
      - apiName: Type
        label: Type
        type: Picklist
        values: [Customer - Direct, Customer - Channel, Channel Partner / Reseller, Installation Partner, Technology Partner, Prospect, Other]
      - apiName: Rating
        label: Rating
        type: Picklist
        values: [Hot, Warm, Cold]
      - apiName: AnnualRevenue
        label: Annual Revenue
        type: Currency
        precision: 18
        scale: 0
      - apiName: NumberOfEmployees
        label: Employees
        type: Number
        precision: 8
        scale: 0
      - apiName: BillingCity
        label: Billing City
        type: Text
        length: 40
      - apiName: BillingState
        label: Billing State
        type: Text
        length: 20
      - apiName: Description
        label: Description
        type: LongTextArea
        length: 1000
        visibleLines: 3
      - apiName: OwnerId
        label: Account Owner
        type: Lookup
        referenceTo: User

  - apiName: Contact
    label: Contact
    pluralLabel: Contacts
    description: People associated with accounts
    fields:
      - apiName: FirstName
        label: First Name
        type: Text
        length: 40
      - apiName: LastName
        label: Last Name
        type: Text
        length: 80
      - apiName: Email
        label: Email
        type: Email
      - apiName: Phone
        label: Phone
        type: Phone
      - apiName: Title
        label: Title
        type: Text
        length: 128
      - apiName: Department
        label: Department
        type: Text
        length: 80
      - apiName: AccountId
        label: Account
        type: Lookup
        referenceTo: Account
      - apiName: LeadSource
        label: Lead Source
        type: Picklist
        values: [Web, Phone Inquiry, Partner Referral, Purchased List, Trade Show, Employee Referral, Advertisement, Other]
      - apiName: MailingCity
        label: Mailing City
        type: Text
        length: 40
      - apiName: MailingState
        label: Mailing State
        type: Text
        length: 20

  - apiName: Lead
    label: Lead
    pluralLabel: Leads
    description: Potential prospects not yet qualified
    fields:
      - apiName: FirstName
        label: First Name
        type: Text
        length: 40
      - apiName: LastName
        label: Last Name
        type: Text
        length: 80
      - apiName: Company
        label: Company
        type: Text
        length: 255
      - apiName: Email
        label: Email
        type: Email
      - apiName: Phone
        label: Phone
        type: Phone
      - apiName: Title
        label: Title
        type: Text
        length: 128
      - apiName: Status
        label: Lead Status
        type: Picklist
        values: [Open - Not Contacted, Working - Contacted, Closed - Converted, Closed - Not Converted]
      - apiName: LeadSource
        label: Lead Source
        type: Picklist
        values: [Web, Phone Inquiry, Partner Referral, Purchased List, Trade Show, Employee Referral, Advertisement, Other]
      - apiName: Industry
        label: Industry
        type: Picklist
        values: [Technology, Manufacturing, Financial Services, Healthcare, Retail, Media, Energy, Education, Government, Consulting, Other]
      - apiName: Rating
        label: Rating
        type: Picklist
        values: [Hot, Warm, Cold]
      - apiName: AnnualRevenue
        label: Annual Revenue
        type: Currency
        precision: 18
        scale: 0
      - apiName: NumberOfEmployees
        label: Employees
        type: Number
        precision: 8
        scale: 0
      - apiName: City
        label: City
        type: Text
        length: 40
      - apiName: State
        label: State
        type: Text
        length: 20
      - apiName: Description
        label: Description
        type: LongTextArea
        length: 1000
        visibleLines: 3
      - apiName: OwnerId
        label: Lead Owner
        type: Lookup
        referenceTo: User

  - apiName: Opportunity
    label: Opportunity
    pluralLabel: Opportunities
    description: Sales deals in pipeline
    fields:
      - apiName: Name
        label: Opportunity Name
        type: Text
        length: 120
      - apiName: AccountId
        label: Account
        type: Lookup
        referenceTo: Account
      - apiName: ContactId
        label: Primary Contact
        type: Lookup
        referenceTo: Contact
      - apiName: Amount
        label: Amount
        type: Currency
        precision: 18
        scale: 0
      - apiName: CloseDate
        label: Close Date
        type: Date
      - apiName: StageName
        label: Stage
        type: Picklist
        values:
          - Prospecting
          - Qualification
          - Needs Analysis
          - Value Proposition
          - Id. Decision Makers
          - Perception Analysis
          - Proposal/Price Quote
          - Negotiation/Review
          - Closed Won
          - Closed Lost
      - apiName: Probability
        label: Probability (%)
        type: Number
        precision: 3
        scale: 0
      - apiName: Type
        label: Type
        type: Picklist
        values: [Existing Customer - Upgrade, Existing Customer - Replacement, Existing Customer - Downgrade, New Customer]
      - apiName: LeadSource
        label: Lead Source
        type: Picklist
        values: [Web, Phone Inquiry, Partner Referral, Purchased List, Trade Show, Employee Referral, Advertisement, Other]
      - apiName: NextStep
        label: Next Step
        type: Text
        length: 255
      - apiName: Description
        label: Description
        type: LongTextArea
        length: 1000
        visibleLines: 3
      - apiName: ForecastCategory
        label: Forecast Category
        type: Picklist
        values: [Pipeline, Best Case, Commit, Omitted, Closed]
      - apiName: CampaignId
        label: Primary Campaign Source
        type: Lookup
        referenceTo: Campaign
      - apiName: OwnerId
        label: Opportunity Owner
        type: Lookup
        referenceTo: User

  - apiName: Case
    label: Case
    pluralLabel: Cases
    description: Customer support cases
    fields:
      - apiName: Subject
        label: Subject
        type: Text
        length: 255
      - apiName: AccountId
        label: Account
        type: Lookup
        referenceTo: Account
      - apiName: ContactId
        label: Contact
        type: Lookup
        referenceTo: Contact
      - apiName: Status
        label: Status
        type: Picklist
        values: [New, Working, Escalated, On Hold, Closed]
      - apiName: Priority
        label: Priority
        type: Picklist
        values: [High, Medium, Low]
      - apiName: Origin
        label: Case Origin
        type: Picklist
        values: [Phone, Email, Web, Chat]
      - apiName: Type
        label: Type
        type: Picklist
        values: [Mechanical, Electrical, Electronic, Structural, Other, Feature Request, Bug]
      - apiName: Reason
        label: Case Reason
        type: Picklist
        values: [Installation, Equipment Complexity, Performance, Breakdown, Equipment Design, Feedback, Other]
      - apiName: Description
        label: Description
        type: LongTextArea
        length: 2000
        visibleLines: 5
      - apiName: CaseNumber
        label: Case Number
        type: Text
        length: 30
      - apiName: OwnerId
        label: Case Owner
        type: Lookup
        referenceTo: User

  - apiName: Campaign
    label: Campaign
    pluralLabel: Campaigns
    description: Marketing campaigns
    fields:
      - apiName: Name
        label: Campaign Name
        type: Text
        length: 80
      - apiName: Type
        label: Type
        type: Picklist
        values: [Conference, Webinar, Trade Show, Public Relations, Partners, Referral Program, Advertisement, Banner Ads, Direct Mail, Email, Telemarketing, Other]
      - apiName: Status
        label: Status
        type: Picklist
        values: [Planned, In Progress, Completed, Aborted]
      - apiName: StartDate
        label: Start Date
        type: Date
      - apiName: EndDate
        label: End Date
        type: Date
      - apiName: BudgetedCost
        label: Budgeted Cost
        type: Currency
        precision: 18
        scale: 0
      - apiName: ActualCost
        label: Actual Cost
        type: Currency
        precision: 18
        scale: 0
      - apiName: ExpectedRevenue
        label: Expected Revenue
        type: Currency
        precision: 18
        scale: 0
      - apiName: NumberSent
        label: Num Sent
        type: Number
        precision: 8
        scale: 0
      - apiName: IsActive
        label: Active
        type: Checkbox
        defaultValue: true
      - apiName: Description
        label: Description
        type: LongTextArea
        length: 1000
        visibleLines: 3
      - apiName: ExpectedResponse
        label: Expected Response (%)
        type: Number
        precision: 5
        scale: 2
      - apiName: NumberOfLeads
        label: Leads Generated
        type: Number
        precision: 8
        scale: 0
      - apiName: NumberOfOpportunities
        label: Opportunities Generated
        type: Number
        precision: 8
        scale: 0
      - apiName: AmountWonOpportunities
        label: Won Opportunity Amount
        type: Currency
        precision: 18
        scale: 0
      - apiName: OwnerId
        label: Campaign Owner
        type: Lookup
        referenceTo: User

  - apiName: Task
    label: Task
    pluralLabel: Tasks
    description: Activities and tasks
    fields:
      - apiName: Subject
        label: Subject
        type: Text
        length: 255
      - apiName: WhoId
        label: Name (Who)
        type: Lookup
        referenceTo: Contact
      - apiName: WhatId
        label: Related To (What)
        type: Lookup
        referenceTo: Account
      - apiName: Status
        label: Status
        type: Picklist
        values: [Not Started, In Progress, Completed, Waiting on someone else, Deferred]
      - apiName: Priority
        label: Priority
        type: Picklist
        values: [High, Normal, Low]
      - apiName: ActivityDate
        label: Due Date
        type: Date
      - apiName: Description
        label: Comments
        type: LongTextArea
        length: 1000
        visibleLines: 3
      - apiName: OwnerId
        label: Assigned To
        type: Lookup
        referenceTo: User
      - apiName: IsCompleted
        label: Completed
        type: Checkbox
        defaultValue: false

  - apiName: Product2
    label: Product
    pluralLabel: Products
    description: Products and services catalog
    fields:
      - apiName: Name
        label: Product Name
        type: Text
        length: 255
      - apiName: ProductCode
        label: Product Code
        type: Text
        length: 30
      - apiName: Description
        label: Product Description
        type: LongTextArea
        length: 1000
        visibleLines: 3
      - apiName: Family
        label: Product Family
        type: Picklist
        values: [Software, Hardware, Support, Services, Training]
      - apiName: IsActive
        label: Active
        type: Checkbox
        defaultValue: true
      - apiName: UnitPrice
        label: Unit Price
        type: Currency
        precision: 18
        scale: 2

  - apiName: User
    label: User
    pluralLabel: Users
    description: System users
    fields:
      - apiName: Username
        label: Username
        type: Text
        length: 80
      - apiName: LastName
        label: Last Name
        type: Text
        length: 80
      - apiName: FirstName
        label: First Name
        type: Text
        length: 40
      - apiName: Email
        label: Email
        type: Email
      - apiName: IsActive
        label: Active
        type: Checkbox
        defaultValue: true
      - apiName: Title
        label: Title
        type: Text
        length: 80
      - apiName: Department
        label: Department
        type: Text
        length: 80

dashboard:
  title: Sales Cloud Dashboard
  widgets:
    - type: pipeline
      object: Opportunity
      field: StageName
      title: Sales Pipeline
    - type: count
      object: Opportunity
      title: Open Opportunities
    - type: count
      object: Lead
      title: Open Leads
    - type: count
      object: Account
      title: Total Accounts
    - type: count
      object: Case
      title: Open Cases
